### ISSUE TITLE
Revenue generation for RecipeRadar

### ISSUE THREAD

**Issue by SumeetMoray** [openculinary/frontend#76]
@jayaddison 

Hi dont know if this is a right place to put this. But i just had few suggestions and wanted to have a discussion. 

You know i love cooking too ... and i cook for myself also. 
I think this is a very useful and interesting project / concept  for anyone who loves and enjoys cooking. 

Have you ever thought about commercializing this project ? I have a suggestion for you. 
You can charge for API requests just like Google Maps charge for API requests. 

And provide some integrations. People can use these integrations to use meal planner in their apps (example : meal planner in a food delivery app) and these people will pay you for API access also ! Just like people pay to Google Maps for API requests. 

I have an idea. I would like to use this integration in my Nearby Shops app. Which we can name as meal planner. It would be something nice for people who wants to buy Groceries and Food Items.

**Comment by jayaddison** [comment]
Thanks @SumeetMoray for creating this issue and the ideas so far.

I believe that users are a democratizing force and that they should have a voice and hand in how the RecipeRadar application works.

That means that they should be able to modify RecipeRadar and use it as a tool the way they'd like to, the same way that anyone can use a pencil and paper at home to plan recipes and shopping lists in their own style.

Given that software and code can be copied for free (that is, more cheaply than a pencil and paper), I don't currently see a reason to charge for the software or use of it.

People may want to fork the code and run their own versions, and I think that's fine.  Wherever possible it'd be good to loop changes back into a core version of RecipeRadar as soon as possible - as long as those do not negatively affect other users (that's another story and will require QA and testing).

Given all this, I think it's still possible for the core RecipeRadar project to generate revenue.  Food suppliers and distributors are paid by users when they order their shopping, and people are accustomed to paying for their food.

What the project needs to determine is -- how can (or should) RecipeRadar legitimately and honestly receive a fair amount of that ingredient purchase transaction.

You could argue that shops should pay for RecipeRadar development, so that the site would work well for their shops and businesses.  That's possible although it could lead to businesses accidentally excluding / causing problems for people elsewhere in the world who are based in environments where those businesses don't exist - or where ingredient shopping is done differently.

Truthfully I don't know what the answer is yet, and while the hosting and development costs for RecipeRadar remain low, I believe it's fine to continue building users, developers and audience without determining that revenue model yet.  It's important to discuss though, and this issue is useful to have on record.

**Comment by jayaddison** [comment]
@SumeetMoray Would you mind opening a separate issue for potential API integration(s)?

**Comment by SumeetMoray** [comment]
Well how to charge and generate revenue i would leave that to you !  And that's a really good thing that you want to keep it free and open source. 

But i would like to point out that you can generate revenue despite keeping the project free and open - source.  There are examples which you can see https://ghost.org and https://discourse.org

**Comment by jayaddison** [comment]
Yep, there are definitely various revenue models available.

My preference is to gather revenue at the point-of-transaction (i.e. some small credit is provided to RecipeRadar in return for facilitating a mutually-beneficial transaction between user and food vendor), and/or via voluntary, informed payment contributions from users.

No payment will be required to use the application and no advertising or tracking-related revenue will be gathered.

**Comment by SumeetMoray** [comment]
Sure we will explore various options we can have regarding revenue generation !

**Comment by jayaddison** [comment]
Closing this for now; revenue generation to be revisited at a later date once the active audience for the application has increased.
