### ISSUE TITLE
Missing icons on sending screenshot of feedback feature

### ISSUE THREAD

**Issue by queencitra** [openculinary/frontend#93]
**Describe the bug**
Tried to send feedback from `feedback` feature. I saw some missing icons to remove the recipe and link to go back to search menu on my screenshot that I'm going to send.

**To Reproduce**
1. Click on `feedback`
2. Leave a blank and click `continue`
3. Click on `review` on send your feedback pop-up

**Expected behavior**
No missing icons from the screenshot sending as feedback

**Screenshots**
<img width="1170" alt="Screen Shot 2020-04-11 at 08 25 07" src="https://user-images.githubusercontent.com/55746560/79032102-070d1a00-7bce-11ea-9232-b404a0a1b687.png">

**Comment by jayaddison** [comment]
This is likely to be an issue somewhere in the [local copy](https://github.com/openculinary/frontend/blob/8cf4647bb503d3542cdd14752c89baae135ff505/src/feedback/feedback.js) of [feedback.js](https://github.com/niklasvh/feedback.js) that we are using, or one of the dependencies within it.

**Comment by jayaddison** [comment]
(this issue should remain tracked here; we may also want to report this upstream to @niklasvh, although the local modifications to their original code are fairly extensive and there's no expectation of support or warranty)

**Comment by jayaddison** [comment]
@queencitra could you have a look at [icon-related issues](https://github.com/niklasvh/html2canvas/issues?q=is%3Aissue+is%3Aopen+icon) in [html2canvas](https://github.com/niklasvh/html2canvas) and see if this might be an existing issue (perhaps with any available workarounds?)

**Comment by jayaddison** [comment]
This is an interesting situation - it turns out that the problem here relates to the presence of spaces inside the [FontAwesome v5.13.0 font-family values](https://github.com/FortAwesome/Font-Awesome/blob/4e6402443679e0a9d12c7401ac8783ef4646657f/css/all.min.css).

[html2canvas](https://github.com/niklasvh/html2canvas) reads but does not re-quote these values when rendering to a canvas.  That leads to a failure of the renderer to identify the correct font to use.

There's a fix pending in https://github.com/niklasvh/html2canvas/pull/1948 and I've provided a little feedback on that change.

**Comment by jayaddison** [comment]
Alternative upstream fix opened as https://github.com/niklasvh/html2canvas/pull/2219

**Comment by jayaddison** [comment]
@queencitra This should now be resolved - could you please verify, when you have time?

NB: We do not yet have a test / staging environment, so the change has been deployed to production.
